### ISSUE TITLE
Small typo in the travis.yml file.

### ISSUE THREAD

**Issue by sudoankit** [coala-analyzer/coala#1755]
The travis.yml file has a small typo error, on the commented second line of the file, in the language block.
```
language:
  # The `objective-c` language by default uses a OSX build container. This
  # is the currently supported method of using a OSX xontainer.    <------ Here. (This should be "container")
  - objective-c

env:
  global:
    - PYENV_ROOT=~/.pyenv
    - PATH=$PYENV_ROOT/shims:$PATH
  matrix:
    - PYTHON_VERSION=3.4.2

install:
  - bash .misc/deps.osx.sh

script:
  - bash .misc/tests.sh

notifications:
  email: false
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/b9493488a4edb005c5c6
```
