### ISSUE TITLE
Switch from travis to circleci

### ISSUE THREAD

**Issue by sils1297** [coala-analyzer/coala#653]
circleci is faster and has newer packages thus eases us maintenance.

Things to do:
 - [x] - Make multiple python versions work
 - [x] - make coveralls and codecov work in all branches
 - [x] - Add code to make zanata work
 - [x] - Update zanata and other API keys
 - [ ] - Test if zanata works in master
 - [ ] - Remove relics from travis

**Comment by AbdealiJK** [comment]
```
Unfortunately we don't have first-class support for "build matrices" type testing of multiple versions. There are some hacky ways to do it like what you link to, but we don't have a great solution for it at the moment. It's definitely on our roadmap though, and I'll make sure to let you know when we have it.
```

The hacky way they mentioned is by directly calling `pyenv` (their virtualenv manager) and making it switch environments manually:
```
dependencies:
  cache_directories:
    - .pip-cache
    - .pyenv

  pre:
    - mkdir -p .pip-cache
    - pyenv install -ks 2.6.8
    - pyenv shell 2.6.8
    - pip install --download-cache .pip-cache nose coverage tissue
    - pyenv install -ks 2.7
    - pyenv shell 2.7

test:
  override:
    - pyenv shell 2.6.8
    - nosetests
    - pyenv shell 2.7
    - nosetests
```

Do we want to do this ? Or wait for the build matrix ?
